import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from 'react'

export default function Home() {

  // const[num1, setnum1]=useState('')
  // const[num2, setnum2]=useState('')
  // const[sum, setSum]=useState('')
  // let add=(e)=>{
  //   e.PreventDefault
  //   return setSum(num1+num2)
  //   console.log(sum)
  // }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="notes.js"></script>
      </Head>

      <body>
        <input  type="number" id="num1" placeholder='number1'/>
        <input type="number" id="num2" placeholder='number2'/>
        <button >add</button>

      </body>
    </div>
  )
}
